export enum NotificationStatus {
  TEXT = 'TEXT',
  REMINDER = 'REMINDER',
  BID = 'BID',
  BID_SUBMIT = 'BID_SUBMIT',
  BID_UPDATE = 'BID_UPDATE',
  CREATE_BOOKING = 'CREATE_BOOKING',
  UPDATE_BOOKING = 'UPDATE_BOOKING',
  BOOKING = 'BOOKING',
  REQUEST = 'REQUEST',
  CHAT = 'CHAT',
  SUPPORT = 'SUPPORT',
  OFFER = 'OFFER',
  NEW_SELLER_ADDED = 'NEW_SELLER_ADDED',
  NEW_BUYER_ADDED = 'NEW_BUYER_ADDED',
  NEW_BOOKING_MADE = 'NEW_BOOKING_MADE',
  NEW_REVIEW_ADDED = 'NEW_REVIEW_ADDED'
}


