export enum OtpType {
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  VERIFY_PHONE = 'VERIFY_PHONE',
  UPDATE_PHONE = 'UPDATE_PHONE',
  UPDATE_EMAIL = 'UPDATE_EMAIL',
}
