import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { BuildENV } from 'common/enums';
import {
  Admin,
  Otp,
  Page,
  User,
  AdminSetting,
  Country,
  State,
  City,
  Category,
  Tag,
  UserTag,
  UserFaq,
  UserPortfolio,
  Service,
  Document,
  Images,
  Notification,
  Connect,
  WithdrawRequest,
  Booking,
  BookingDocument,
  BookingImage,
  CompletionProof,
  WalletTransaction,
  PriceRange,
  ResponseTime,
  ChatRequest,
  Chat,
  Report,
  ConnectTransaction,
  ServiceBids,
  UserBankAccount,
  Favorite,
  Banner,
  Offer,
  OfferDocument,
  OfferImage,
  UserReviews,
  Milestone,
  Testimonial,
  SupportRequest,
  Support,
  SocialAccount
} from 'common/models';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => ({
        type: 'mariadb',
        host: configService.get('DB_HOST'),
        port: Number(configService.get('DB_PORT')),
        username: configService.get('DB_USER'),
        password: configService.get('DB_PASS'),
        database: configService.get('DB_NAME'),
        entities: [
          Admin,
          AdminSetting,
          Otp,
          Page,
          User,
          Country,
          State,
          City,
          Category,
          Tag,
          UserTag,
          UserFaq,
          UserPortfolio,
          Service,
          Document,
          Images,
          Notification,
          Connect,
          WithdrawRequest,
          Booking,
          BookingDocument,
          BookingImage,
          CompletionProof,
          WalletTransaction,
          PriceRange,
          ResponseTime,
          ChatRequest,
          Chat,
          Report,
          ConnectTransaction,
          ServiceBids,
          UserBankAccount,
          Favorite,
          UserReviews,
          Banner,
          Offer,
          OfferDocument,
          OfferImage,
          Milestone,
          Testimonial,
          SupportRequest,
          Support,
          SocialAccount
        ],
        // ! ALWAYS FALSE IN PROD
        synchronize: true, // configService.get('NODE_ENV') !== BuildENV.PRODUCTION,
        logging: true,
        extra: {
          // MySQL2 connection pool options
          connectionLimit: 10,
          // MySQL2 connection options
          connectTimeout: 60000, // 60 seconds connection timeout
          enableKeepAlive: true,
          keepAliveInitialDelay: 0,
        },
        retryAttempts: 5,
        retryDelay: 3000, // 3 seconds delay between retries
      }),
    }),
    TypeOrmModule.forFeature([User, Country, City, State, Category, Tag]),
  ],
})
export class DatabaseConfigModule {}
